on: [push, workflow_dispatch]

name: build

jobs:
  check:
    name: pssh-box-rs check/nightly
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
      - uses: taiki-e/install-action@cargo-hack

      - name: Install protoc compiler
        run: |
          sudo apt-get update
          sudo apt-get install protobuf-compiler

      - run: cargo check
      - run: cargo hack check --feature-powerset --no-dev-deps

  test-linux:
    name: linux
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable

      - name: Install protoc compiler
        run: |
          sudo apt-get update
          sudo apt-get install protobuf-compiler

      - run: cargo test --jobs 1 --all-features

  test-windows:
    name: windows
    runs-on: windows-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: msys2/setup-msys2@v2

      - name: install protobuf compiler
        run: choco install --yes --limit-output protoc

      - name: run tests
        shell: msys2 {0}
        run: cargo test --jobs 1 --all-features

  test-macos:
    name: macos
    runs-on: macos-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable

      - name: install protobuf compiler
        run: brew install protobuf

      - run: cargo test --jobs 1 --all-features
